name: Weekly Article Selection and Deployment

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 9 * * 1' # Runs every Monday at 9:00 AM UTC

permissions:
  contents: write # Needed to commit changes back to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify a Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Inoreader token file from secrets
        run: |
          mkdir -p Data
          echo '{
            "client_id": "${{ secrets.INOREADER_CLIENT_ID }}",
            "client_secret": "${{ secrets.INOREADER_CLIENT_SECRET }}",
            "refresh_token": "${{ secrets.INOREADER_REFRESH_TOKEN }}",
            "access_token": "",
            "token_expiry": 0
          }' > Data/token.json

      - name: Run weekly workflow script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          INOREADER_APP_ID: ${{ secrets.INOREADER_APP_ID }}
          INOREADER_APP_KEY: ${{ secrets.INOREADER_APP_KEY }}
          FEEDBACK_APP_URL: ${{ secrets.FEEDBACK_APP_URL }}
        run: python Code/scheduler_app.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Weekly article update"
          file_pattern: "docs/index.html Data/*.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
